#!/bin/bash

# set range below to limit the number of folders autogenerated. Default: 128

# line 10: mkdir creates a directory with just a number
# line 11: mv will move all files matching the search pattern into the folder that was created 

# line 14: find and delete any empty folders within the directory

for i in {1..128}; do
    mkdir -p "$i" && 
    mv *."$i".wav "$i"
done

find . -type d -empty -delete


